# Topic Explorer Notebook Tutorial

The InPhO Topic Explorer features a powerful interactive coding environment that enables direct manipulation of the corpus and models, in contrast to the web visualization.

When you run the `vsm notebook` command, several things happen:
1.  The Topic Explorer creates a new folder called `notebooks` and places several files inside it:
     -  **corpus.py** contains Python code which imports the Corpus object and a function that will load models trained on your corpus. It gathers this information from your `CORPUS.ini` file, where `CORPUS` is the name of the folder you prepared. More information on this special file is below.
     -  **Topic Explorer Tutorial.ipynb** is this file, which provides the skeleton documentation for interacting with the models.
     -  Other **ipynb** files, containing analyses that can be re-run on your own corpora.
2.  The Topic Explorer launches a [Jupyter Notebook](http://jupyter.org/). This allows you to program in Python on your local computer using the browser, rather than a terminal or other program.

## Importing `corpus.py`
Now that you know how to run a cell, we can begin interacting with the topic models. First we will import your corpus objects. Select and run the cell below:

In [2]:
from corpus import *

ModuleNotFoundError: No module named 'future'

You will now have access to several variables, the most important of which are:
 -  `c` -- The `vsm.Corpus` object
 -  `lda_v` -- A dictionary containing each of the `vsm.LdaViewer` instances. You can access a particular model with `lda_v[k]`, substituting k for a particular number, like `lda_v[20]` for the 20-topic model. If the model for that number of topics has not been trained, it will error.
 -  `topic_range` -- A list of the trained models (e.g., `[20, 40, 60, 80]`)
 -  `context_type` -- A string containing the particular context type modeled (e.g., `"sentence"`, `"document"`, `"article"`)

### Introducing the `vsm` module

The InPhO Topic Explorer is comprised of two modules:
1. The `topicexplorer` module contains code for the visualization and user interfaces.
2. The `vsm` module contains code for modeling differnet corpora. 

In order to make use of the term frequency (TF), term frequency-inverse document frequency (TfIdf), and latent semantic analysis (LSA) models, we must import the main vsm module:

In [22]:
from vsm import *

## Interacting with the Corpus: Term Frequencies

The command above has loaded your `Corpus` object into the `c` variable. You can see the list of all words that are in your corpus by typing `c.words` into a code cell:

In [23]:
c.words

array(['aa', 'aaa', 'aaaa', ..., '풪', '︷', '︸'], dtype=object)

Note that it only shows the first few and last few unique words in the corpus, alphabetically sorted. 

What if we want to get a list of how often each word occurs? For that, we can use the `vsm.model.TF` to build a frequency distribution over the terms in the corpus:

In [24]:
# train the model and create a TfViewer object
tf = TF(c, context_type)
tf.train()
tf_v = TfViewer(c, tf)

# print the most frequent terms in the document
# remember that IPython automatically prints the last cell of a document
tf_v.coll_freqs()

LabeledColumn([('model', 79858), ('f', 74037), ('q', 63823), ...,
               ('nonidentifying',     2), ('dmi',     2),
               ('maxdy',     2)],
              dtype=[('word', '<U62'), ('value', '<i8')])

After running the cell above, you should see a table with the 20 most frequently used words.

## Interacting with Topic Models

The InPhO Topic Explorer doesn't just work with term frequencies though - it creates LDA topic models. Through the notebook interface these models can be powerfully manipulated to produce new analyses.

First, let's select a primary model to investigate, and load it into the variable `v`:

In [25]:
topic_num = 0
# print the number of topics in the first model
print(topic_range[topic_num])
# remember that list indexes start with 0 not 1!

# replace 'topic_range[0]' with a specific number, if you like
k = topic_range[topic_num]

# load the topic model
v = lda_v[k]

20

The above code loads the first topic model into a viewer object. We have used the `topic_range[0]` instead of simply stating a number so that this same demo notebook will work with any model settings you've prepared. This portability enables us to write analyses that can be replicated across any corpus, and is one of the real strengths of using the `from corpus import *` model of coding your notebooks. If others are using the Topic Explorer to generate their objects, they can run the exact same analysis on different corpora, so long as the variable names are consistent

### `v.topics()`
First, lets print a list of topics:

In [26]:
v.topics()

[LabeledColumn([('et', 1.7831322e-02), ('al', 1.5591688e-02),
                ('participants', 1.2778989e-02), ...,
                ('model', 1.9035179e-08), ('probability', 1.9035179e-08),
                ('probabilities', 1.9035179e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('item', 1.8723859e-02), ('set', 1.6397031e-02),
                ('items', 1.0185160e-02), ..., ('≤', 4.1016101e-08),
                ('w', 4.1016101e-08), ('δ', 4.1016101e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('space', 1.1346714e-02), ('stimulus', 1.0139556e-02),
                ('stimuli', 8.9560691e-03), ...,
                ('replies', 2.9587152e-08), ('fsmds', 2.9587152e-08),
                ('aa', 2.9587152e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('model', 2.0678805e-02), ('learning', 1.6718490e-02),
                ('category', 1.2606424e-02), ..., ('rosen', 3.7012260e-08),
                ('roschian', 3.7012260e-08), ('aa', 3.7012260e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('utility', 1.9942729e-02), ('decision', 1.5737034e-02),
                ('risk', 1.3123138e-02), ...,
                ('transcendental', 3.3511469e-08),
                ('submodels', 3.3511469e-08), ('∈', 3.2726078e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('u', 7.9492174e-02), ('α', 3.3635315e-02),
                ('β', 3.2659017e-02), ..., ('fixedlength', 3.2435153e-08),
                ('samples', 3.2435153e-08), ('︸', 3.2435153e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('memory', 2.5993897e-02), ('items', 1.5769666e-02),
                ('item', 1.5334666e-02), ..., ('ridge', 3.4251993e-08),
                ('riddled', 3.4251993e-08), ('︸', 3.4251993e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('f', 2.6528398e-02), ('e', 2.4495983e-02),
                ('z', 2.1127639e-02), ..., ('fxc', 2.3770923e-08),
                ('retinally', 2.3770923e-08), ('︸', 2.3770923e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('response', 2.2784494e-02), ('model', 2.2615880e-02),
                ('learning', 2.0356970e-02), ...,
                ('marcum', 2.6764297e-08), ('marczewska', 2.6764297e-08),
                ('maxdy', 2.6764297e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('state', 1.6622949e-02), ('quantum', 1.4929453e-02),
                ('probability', 1.2474833e-02), ...,
                ('fletcherpowell', 3.8056083e-08),
                ('rtresearch', 3.8056083e-08), ('aa', 3.8056083e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('one', 2.1907536e-02), ('two', 1.9953560e-02),
                ('model', 1.7862890e-02), ..., ('item', 5.1740248e-09),
                ('stimuli', 5.1740248e-09), ('proposition', 5.1740248e-09)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('model', 4.7398314e-02), ('data', 2.7909886e-02),
                ('models', 2.0656325e-02), ..., ('≤', 1.5126108e-08),
                ('⋅', 1.5126108e-08), ('λ', 1.5126108e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('f', 8.3647974e-02), ('σ', 5.2904967e-02),
                ('μ', 4.6585765e-02), ..., ('θ', 3.1198656e-08),
                ('ϕ', 3.1198656e-08), ('ω', 3.1198656e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('∈', 6.5812290e-02), ('z', 4.4626985e-02),
                ('f', 2.4575856e-02), ..., ('stahl', 2.0003103e-08),
                ('notthe', 2.0003103e-08), ('vehicles', 2.0003103e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('e', 2.9651018e-02), ('g', 2.1478537e-02),
                ('let', 1.3876706e-02), ..., ('rotates', 2.2644697e-08),
                ('maxdy', 2.2644697e-08), ('ϕ', 2.2113984e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('time', 2.9852744e-02), ('processing', 1.7103627e-02),
                ('response', 1.6134683e-02), ...,
                ('kochenspecker', 2.8837603e-08),
                ('kowalchuk', 2.8837603e-08), ('λ', 2.8161748e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('choice', 3.6647450e-02), ('set', 2.2050343e-02),
                ('preference', 1.5498851e-02), ...,
                ('fcuwp', 4.3560409e-08), ('fcuwq', 4.3560409e-08),
                ('qktvk', 4.3560409e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('θ', 8.0177814e-02), ('α', 5.9952885e-02),
                ('π', 5.7655107e-02), ..., ('xα⊕α≻', 2.8090147e-08),
                ('questions', 2.8090147e-08), ('embodies', 2.8090147e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('function', 1.7919905e-02), ('models', 1.6640840e-02),
                ('given', 1.5973849e-02), ..., ('response', 9.7508766e-09),
                ('probability', 9.7508766e-09), ('items', 9.7508766e-09)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('q', 1.6761938e-01), ('∈', 5.6370370e-02),
                ('l', 2.5291942e-02), ..., ('sadly', 3.1603008e-08),
                ('reconciliation', 3.1603008e-08), ('z', 3.0862342e-08)],
               dtype=[('word', 'O'), ('value', '<f4')])]

To change the number of words printed per topic, use the `print_len` argument:

In [27]:
v.topics(print_len=20)

[LabeledColumn([('et', 1.7831322e-02), ('al', 1.5591688e-02),
                ('participants', 1.2778989e-02), ...,
                ('model', 1.9035179e-08), ('probability', 1.9035179e-08),
                ('probabilities', 1.9035179e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('item', 1.8723859e-02), ('set', 1.6397031e-02),
                ('items', 1.0185160e-02), ..., ('≤', 4.1016101e-08),
                ('w', 4.1016101e-08), ('δ', 4.1016101e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('space', 1.1346714e-02), ('stimulus', 1.0139556e-02),
                ('stimuli', 8.9560691e-03), ...,
                ('replies', 2.9587152e-08), ('fsmds', 2.9587152e-08),
                ('aa', 2.9587152e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('model', 2.0678805e-02), ('learning', 1.6718490e-02),
                ('category', 1.2606424e-02), ..., ('rosen', 3.7012260e-08),
                ('roschian', 3.7012260e-08), ('aa', 3.7012260e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('utility', 1.9942729e-02), ('decision', 1.5737034e-02),
                ('risk', 1.3123138e-02), ...,
                ('transcendental', 3.3511469e-08),
                ('submodels', 3.3511469e-08), ('∈', 3.2726078e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('u', 7.9492174e-02), ('α', 3.3635315e-02),
                ('β', 3.2659017e-02), ..., ('fixedlength', 3.2435153e-08),
                ('samples', 3.2435153e-08), ('︸', 3.2435153e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('memory', 2.5993897e-02), ('items', 1.5769666e-02),
                ('item', 1.5334666e-02), ..., ('ridge', 3.4251993e-08),
                ('riddled', 3.4251993e-08), ('︸', 3.4251993e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('f', 2.6528398e-02), ('e', 2.4495983e-02),
                ('z', 2.1127639e-02), ..., ('fxc', 2.3770923e-08),
                ('retinally', 2.3770923e-08), ('︸', 2.3770923e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('response', 2.2784494e-02), ('model', 2.2615880e-02),
                ('learning', 2.0356970e-02), ...,
                ('marcum', 2.6764297e-08), ('marczewska', 2.6764297e-08),
                ('maxdy', 2.6764297e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('state', 1.6622949e-02), ('quantum', 1.4929453e-02),
                ('probability', 1.2474833e-02), ...,
                ('fletcherpowell', 3.8056083e-08),
                ('rtresearch', 3.8056083e-08), ('aa', 3.8056083e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('one', 2.1907536e-02), ('two', 1.9953560e-02),
                ('model', 1.7862890e-02), ..., ('item', 5.1740248e-09),
                ('stimuli', 5.1740248e-09), ('proposition', 5.1740248e-09)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('model', 4.7398314e-02), ('data', 2.7909886e-02),
                ('models', 2.0656325e-02), ..., ('≤', 1.5126108e-08),
                ('⋅', 1.5126108e-08), ('λ', 1.5126108e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('f', 8.3647974e-02), ('σ', 5.2904967e-02),
                ('μ', 4.6585765e-02), ..., ('θ', 3.1198656e-08),
                ('ϕ', 3.1198656e-08), ('ω', 3.1198656e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('∈', 6.5812290e-02), ('z', 4.4626985e-02),
                ('f', 2.4575856e-02), ..., ('stahl', 2.0003103e-08),
                ('notthe', 2.0003103e-08), ('vehicles', 2.0003103e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('e', 2.9651018e-02), ('g', 2.1478537e-02),
                ('let', 1.3876706e-02), ..., ('rotates', 2.2644697e-08),
                ('maxdy', 2.2644697e-08), ('ϕ', 2.2113984e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('time', 2.9852744e-02), ('processing', 1.7103627e-02),
                ('response', 1.6134683e-02), ...,
                ('kochenspecker', 2.8837603e-08),
                ('kowalchuk', 2.8837603e-08), ('λ', 2.8161748e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('choice', 3.6647450e-02), ('set', 2.2050343e-02),
                ('preference', 1.5498851e-02), ...,
                ('fcuwp', 4.3560409e-08), ('fcuwq', 4.3560409e-08),
                ('qktvk', 4.3560409e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('θ', 8.0177814e-02), ('α', 5.9952885e-02),
                ('π', 5.7655107e-02), ..., ('xα⊕α≻', 2.8090147e-08),
                ('questions', 2.8090147e-08), ('embodies', 2.8090147e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('function', 1.7919905e-02), ('models', 1.6640840e-02),
                ('given', 1.5973849e-02), ..., ('response', 9.7508766e-09),
                ('probability', 9.7508766e-09), ('items', 9.7508766e-09)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('q', 1.6761938e-01), ('∈', 5.6370370e-02),
                ('l', 2.5291942e-02), ..., ('sadly', 3.1603008e-08),
                ('reconciliation', 3.1603008e-08), ('z', 3.0862342e-08)],
               dtype=[('word', 'O'), ('value', '<f4')])]

In [28]:
len(list(v.topics()))

20

In [29]:
list(v.dist_top_doc(18, print_len=len(v.labels)))[:5]

[('1976-Grier-Optimal.txt', 0.65031653),
 ('1985-Osuna-Psychological.txt', 0.65877875),
 ('2015-Kocas-Extension.txt', 0.68119797),
 ('2001-Denuit-Extension.txt', 0.68896347),
 ('1968-Woodbury-Validity.txt', 0.69627366)]

In [30]:
v.dist_top_doc(18)

LabeledColumn([('1976-Grier-Optimal.txt', 0.65031653),
               ('1985-Osuna-Psychological.txt', 0.65877875),
               ('2015-Kocas-Extension.txt', 0.68119797), ...,
               ('2020-Giarlotta-Bi_preference.txt', 0.999995  ),
               ('2018-Boehm-Across_trial.txt', 0.99999573),
               ('1995-Dzhafarov-Decompositions.txt', 0.99999636)],
              dtype=[('doc', '<U48'), ('value', '<f8')])

In [31]:
len(v.labels)

1978

In [32]:
help(v.dist_top_doc)

Help on method dist_top_doc in module vsm.viewer.ldacgsviewer:

dist_top_doc(topic_or_topics, weights=[], filter_words=[], print_len=10, as_strings=True, label_fn=<function def_label_fn at 0x7f96d8182830>, filter_nan=True, dist_fn=<function JS_dist at 0x7f96f81737a0>, order='i') method of vsm.viewer.ldacgsviewer.LdaCgsViewer instance
    Takes a topic or list of topics (by integer index) and returns
    a list of documents sorted by distance.

    :param topic_or_topics: Query topic(s) relative to which
        distances are computed.
    :type topic_or_topics: string or list of strings

    :param weights: Specify weights for each topic in `topic_or_topics`.
        Default uses equal weights (i.e. arithmetic mean)
    :type weights: list of floating point, optional

    :param filter_words: The topics that include these words are considered.
        If not provided, by default all topics are considered.
    :type filter_words: list of words, optional

    :param print_len: Number of documents printed by pretty-pringing function
        Default is 10.
    :type print_len: int, optional

    :param as_strings: If `True`, returns a list of documents as strings rather
        than their integer representations. Default is `True`.
    :type as_strings: boolean, optional

    :param label_fn: A function that defines how documents are represented.
        Default is def_label_fn which retrieves the labels from corpus
        metadata.
    :type label_fn: string, optional

    :param filter_nan: If `True` not a number entries are filtered.
        Default is `True`.
    :type filter_nan: boolean, optional

    :param dist_fn: A distance function from functions in vsm.spatial.
        Default is :meth:`JS_dist`.
    :type dist_fn: string, optional

    :param order: Order of sorting. 'i' for increasing and 'd' for
        decreasing order. Default is 'i'.
    :type order: string, optional

    :returns: an instance of :class:`LabeledColumn`.
        A 2-dim array containing documents and their posterior probabilities
        to `topic_or_topics`.

    :See Also: :meth:`def_label_fn`, :meth:`vsm.viewer.wrapper.dist_top_doc`

### Viewing Document-topic probabilities
The above code shows the topic-word distributions and allows us to estimate the quality of our topics.

#### `v.labels`
The property `v.labels` (without parentheses) returns a list of all documents in a corpus, and is useful for processing each document generically, without having to look up the identifiers on the file system.

Below, we print the first 3 document labels:

In [33]:
for label in v.labels[:3]:
    print(label)

1991-Goldstein-Networks.txt
1971-Holman-Note.txt
2019-Burns-Balance.txt

#### `v.doc_topics(doc_or_docs)`
Each document-topic distribution can be examined with `v.doc_topics()`, which takes as its argument either a single label or a list of labels. Below we view the distribution for the first 3 documents.

In [34]:
v.doc_topics(v.labels[:3])

[LabeledColumn([(15, 3.9962411e-01), (10, 3.0489388e-01),
                (18, 1.8068467e-01), ( 7, 6.8565145e-02),
                (14, 2.9480645e-02), ( 8, 1.6066050e-02),
                (19, 6.6410535e-04), ( 6, 1.6564767e-06),
                ( 9, 1.6564767e-06), (12, 1.6561609e-06),
                (13, 1.6561609e-06), ( 4, 1.6561609e-06),
                ( 2, 1.6561609e-06), ( 1, 1.6561609e-06),
                ( 5, 1.6561229e-06), ( 3, 1.6561229e-06),
                (11, 1.6561213e-06), (16, 1.6561213e-06),
                (17, 1.6561213e-06), ( 0, 1.6561213e-06)],
               dtype=[('topic', '<i8'), ('value', '<f4')]),
 LabeledColumn([(14, 5.7712615e-01), ( 7, 2.9869217e-01),
                (10, 7.7632464e-02), (18, 4.6414107e-02),
                (19, 8.4391959e-06), (16, 8.4391959e-06),
                (13, 8.4391959e-06), ( 3, 8.4375861e-06),
                ( 8, 8.4375861e-06), ( 0, 8.4375861e-06),
                (12, 8.4375861e-06), (17, 8.4375861e-06),
                ( 5, 8.4373933e-06), (11, 8.4373851e-06),
                (15, 8.4373851e-06), ( 6, 8.4373851e-06),
                ( 4, 8.4373851e-06), ( 2, 8.4373851e-06),
                ( 1, 8.4373851e-06), ( 9, 8.4373851e-06)],
               dtype=[('topic', '<i8'), ('value', '<f4')]),
 LabeledColumn([(15, 3.4686336e-01), ( 0, 2.9477704e-01),
                (10, 1.6227175e-01), (18, 8.5859425e-02),
                (11, 7.9277083e-02), ( 2, 2.4328889e-02),
                ( 9, 3.4371242e-03), (17, 3.1509358e-03),
                (13, 2.8619509e-06), (14, 2.8619509e-06),
                ( 8, 2.8619509e-06), ( 7, 2.8619509e-06),
                ( 6, 2.8619509e-06), ( 4, 2.8619509e-06),
                ( 3, 2.8619509e-06), (19, 2.8619509e-06),
                (12, 2.8618824e-06), (16, 2.8618824e-06),
                ( 5, 2.8618824e-06), ( 1, 2.8618824e-06)],
               dtype=[('topic', '<i8'), ('value', '<f4')])]

#### `v.aggregate_doc_topics(doc_or_docs, normed_sum=False)`
While `v.doc_topics(doc_or_docs)` shows the distribution for each document, `v.aggregate_doc_topics()` shows the average distribution of a collection of documents. The `normed` argument tells the program whether to weight each document by its length (`normed_sum=True`) or to consider them all equally (`normed_sum=False`).

In [35]:
v.aggregate_doc_topics(v.labels, normed_sum=True)

LabeledColumn([(10, 0.21088506), (18, 0.11492805), (11, 0.06698292),
               ( 7, 0.06247863), (14, 0.05919559), ( 0, 0.0539473 ),
               ( 8, 0.04939574), ( 2, 0.03830776), ( 4, 0.0353466 ),
               (13, 0.03401882), (15, 0.03262845), (17, 0.02995597),
               ( 9, 0.02973689), ( 6, 0.02928461), (12, 0.02694227),
               ( 5, 0.02668685), ( 1, 0.02560325), ( 3, 0.02474431),
               (19, 0.02464568), (16, 0.02428525)],
              dtype=[('i', '<i8'), ('value', '<f4')])

### Comparing documents with `v.dist()`

Topic models give us a way to compare the siimilarity between two documents. To do this, we use `v.dist()`:

In [36]:
v.dist(v.labels[0], v.labels[1])

0.7517058605733435

#### Alternative distance measures
By default, the Topic Explorer uses the Jensen-Shannon Distance to calculate the distance between documents. The Jensen-Shannon Distance (JSD) is a symmetric measure based on information theory that characterizes the difference between two probability distributions.

However, several alternate methods are built into the `vsm.spatial` module. These include the Kullback-Leibler Divergence, which is an asymmetric component of the JSD and is used in [Murdock et al. (2017)](http://arxiv.org/abs/1509.07175) to characterize the cognitive surprise of a new text, given previous texts.

Rather than using the JSD and assuming symmetric divergence between items, we assume that the second document is encountered after the first, effectively measuring text-to-text divergence.

In [37]:
help(v.dist)

Help on method dist in module vsm.viewer.ldacgsviewer:

dist(doc1, doc2, dist_fn=<function JS_dist at 0x7f96f81737a0>) method of vsm.viewer.ldacgsviewer.LdaCgsViewer instance
    Computes the distance between 2 documents in topic space.

    :param doc1: Query document
    :type doc1: string/integer

    :param doc2: Query document
    :type doc2: string/integer

    :param dist_fn: A distance function from functions in vsm.spatial.
        Default is :meth:`JS_dist`.
    :type dist_fn: string, optional

    :returns: an instance of `LabeledColumn`.
        A 2-dim array containing documents and their distances to
        `doc_or_docs`.

In [38]:
# first import KL divergence:
from vsm.spatial import KL_div

# calculate KL divergence from the first document to the second
print("First to second", v.dist(v.labels[0], v.labels[1], dist_fn=KL_div))

# calculate KL divergence from the second document to the first, highlighting asymmetry:
print("Second to first", v.dist(v.labels[1], v.labels[0], dist_fn=KL_div))

First to second 7.069877362528501
Second to first 2.866389634947721

# Citation network

## Gets df for getting citation count

In [39]:
import pandas as pd
import heapq
import re

In [46]:
jmp_cbb_articles = pd.read_csv("../jmp_articles_list.csv")
jmp_cbb_articles["title"] = jmp_cbb_articles["title"].apply(lambda t: re.sub(r"[\[\]']", "", t))
jmp_cbb_articles["author"] = jmp_cbb_articles["author"].apply(lambda a: re.sub(r"[\[\]']", "", a))

In [48]:
import glob
import os.path

In [49]:
doi_dict = {}

for file in glob.glob("../jmp_text_files/*.txt"):
    filename = os.path.basename(file)
    with open(file, "r") as f:
        first_line = f.readline().strip()   # strip removes trailing newline
        doi_dict[filename] = first_line

In [50]:
reverse_doi_dict = {val: key for key, val in doi_dict.items()}

jmp_cbb_articles["file_name"] = jmp_cbb_articles["DOI"].map(reverse_doi_dict)
jmp_cbb_articles["cites_per_year"] = round(jmp_cbb_articles["crossref_ref_by_count"] / (2026 - jmp_cbb_articles["issued_year"]), 1)

In [51]:
jmp_cbb_articles.head(5)

,DOI,title,author,volume,issue,issued_year,issued_month,crossref_ref_by_count,gscholar_ref_by_count,journal,file_name,cites_per_year
0,10.1016/0022-2496(64)90021-5,Choice behavior and reward structure,"Jerome L. Myers, Richard C. Atkinson",1,1,1964,1,15.0,50.0,jmp,1964-Myers-Behavior.txt,0.2
1,10.1016/0022-2496(64)90015-x,Simultaneous conjoint measurement: A new type ...,"R.Duncan Luce, John W. Tukey",1,1,1964,1,1350.0,3164.0,jmp,1964-Luce-Conjoint.txt,21.8
2,10.1016/0022-2496(64)90016-1,Point estimation in learning models,Helena Chmura Kraemer,1,1,1964,1,3.0,8.0,jmp,1964-Kraemer-Learning.txt,0.0
3,10.1016/0022-2496(64)90022-7,Transfer effects in discrimination learning,"Morton P. Friedman, Harold Gelfand",1,1,1964,1,9.0,38.0,jmp,1964-Friedman-Discrimination.txt,0.1
4,10.1016/0022-2496(64)90018-5,"Sensory thresholds, response biases, and the n...",Donald A. Norman,1,1,1964,1,53.0,64.0,jmp,"1964-Norman-Thresholds,.txt",0.9

## Gets KL divergence values and JSD values

In [52]:
topic_num = 0
# print the number of topics in the first model
print(topic_range[topic_num])

# replace 'topic_range[0]' with a specific number, if you like
k = topic_range[topic_num]

# load the topic model
v = lda_v[k]

20

In [53]:
filtered_df = jmp_cbb_articles.loc[(jmp_cbb_articles["cites_per_year"] >= 4) & (jmp_cbb_articles["journal"] == "jmp")]

In [54]:
filtered_df.shape

(164, 12)

In [55]:
edges = []

for i, source in enumerate(filtered_df["file_name"]):
    for j, target in enumerate(filtered_df["file_name"]):
        if i == j:
            continue

        kl = v.dist(source, target, dist_fn=KL_div)
        jsd = v.dist(source, target)

        edges.append({
            "source": source,
            "doi_source": doi_dict.get(source),
            "target": target,
            "doi_target": doi_dict.get(target),
            "kl": kl,
            "jsd": jsd
        })

edges_df = pd.DataFrame(edges)

In [56]:
edges_df.head(5)

,doi_source,doi_target,jsd,kl,source,target
0,10.1016/0022-2496(64)90015-x,10.1016/0022-2496(64)90017-3,0.774555,12.691160,1964-Luce-Conjoint.txt,1964-Shepard-Metric.txt
1,10.1016/0022-2496(64)90015-x,10.1016/0022-2496(64)90002-1,0.194539,0.352375,1964-Luce-Conjoint.txt,1964-Scott-Structures.txt
2,10.1016/0022-2496(64)90015-x,10.1016/0022-2496(66)90002-2,0.441871,0.840638,1964-Luce-Conjoint.txt,1966-Novick-Axioms.txt
3,10.1016/0022-2496(64)90015-x,10.1016/0022-2496(66)90017-4,0.676823,5.222843,1964-Luce-Conjoint.txt,1966-Shepard-Structures.txt
4,10.1016/0022-2496(64)90015-x,10.1016/0022-2496(69)90019-4,0.669728,7.665662,1964-Luce-Conjoint.txt,1969-Dorfman-Parameters.txt

## K-means clusters using JSD values

In [57]:
import numpy as np
import random
import networkx as nx
from pyvis.network import Network
from sklearn.manifold import MDS
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

In [58]:
dois = filtered_df["DOI"].astype(str).str.strip().tolist()
idx = {d:i for i,d in enumerate(dois)}
n = len(dois)

D = np.zeros((n, n), dtype=float)

for _, r in edges_df.iterrows():
    i = idx.get(str(r["doi_source"]).strip())
    j = idx.get(str(r["doi_target"]).strip())
    if i is None or j is None:
        continue
    D[i, j] = float(r["jsd"])

# If edges_df is directional duplicates, symmetrize:
D = 0.5 * (D + D.T)
np.fill_diagonal(D, 0.0)

In [59]:
X = MDS(n_components=2, dissimilarity="precomputed", random_state=42).fit_transform(D)  # 2 components for 2D

In [60]:
edges_df["jsd_sim"] = np.exp(-edges_df["jsd"])

In [61]:
edges_top5 = (
    edges_df
    .groupby("doi_source", group_keys=False)
    .apply(lambda x: x.nsmallest(5, "jsd"))
)

min_jsd_sim = edges_top5["jsd_sim"].min()
max_jsd_sim = edges_top5["jsd_sim"].max()

edges_top5["scaled_jsd_sim"] = (
    (edges_top5["jsd_sim"] - min_jsd_sim) /
    (max_jsd_sim - min_jsd_sim)
)

edges_top5["edge_width"] = 1 + edges_top5["scaled_jsd_sim"] * 8

In [62]:
# Scales number of citations to make node size differences more visible
cites = filtered_df["crossref_ref_by_count"].fillna(0)

log_cites = np.log1p(cites)
scaled = (log_cites - log_cites.min()) / (log_cites.max() - log_cites.min())
filtered_df["node_size"] = 15 + 50 * scaled

/opt/anaconda3/envs/py37/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [63]:
G = nx.Graph()

# Adds nodes
for file in filtered_df["file_name"]:
    G.add_node(file)
    
# Adds edges
for _, r in edges_top5.iterrows():
    G.add_edge(
        r["source"],
        r["target"],
        value=r["edge_width"],
        title=f"JSD: {r['jsd']:.3f}"
    )

# Computes force layout
pos = nx.spring_layout(G, seed=42, k=0.5)

# Extracts coordinates from force layout
papers = list(G.nodes())
X_force = np.array([pos[p] for p in papers])

In [64]:
"""
Computes silhouette score for 2-10 clusters
(this is a measure of how well each paper fits within its
assigned cluster relative to the closest cluster)
"""
scores = []
ks = range(2, 11)

for k in ks:
    labels = KMeans(n_clusters=k, random_state=42, n_init=20).fit_predict(X_force)
    score = silhouette_score(X_force, labels)
    scores.append(score)
    print(f"k={k}, silhouette={score:.3f}")

k=2, silhouette=0.385
k=3, silhouette=0.424
k=4, silhouette=0.379
k=5, silhouette=0.378
k=6, silhouette=0.390
k=7, silhouette=0.386
k=8, silhouette=0.383
k=9, silhouette=0.389
k=10, silhouette=0.399

In [65]:
# Saves clusters for 3, 5, and 10 clusters in the network
k_values = [3, 5, 10]

cluster_results = {}

for k in k_values:
    labels = KMeans(n_clusters=k, random_state=42).fit_predict(X_force)
    cluster_results[k] = labels

In [66]:
# Runs k-means on the force layout
k = 10

# Assigns each paper to a cluster
labels = cluster_results[k]
cluster_map = dict(zip(papers, labels))
filtered_df["cluster"] = filtered_df["file_name"].map(cluster_map)

cluster_colors = [
    "#1f77b4",  # strong blue
    "#ff7f0e",  # bright orange
    "#2ca02c",  # green
    "#d62728",  # red
    "#9467bd",  # purple
    "#8c564b",  # brown
    "#e377c2",  # magenta
    "#7f7f7f",  # gray
    "#bcbd22",  # olive
    "#17becf"   # cyan
]
clusters = sorted(set(labels))
color_map = {
    c: cluster_colors[i]
    for i, c in enumerate(sorted(clusters))
}

# Adds visual attributes
metadata = (
    filtered_df
    .set_index("file_name")
    .to_dict(orient="index")
)

for paper in papers:
    x, y = pos[paper]
    info = metadata[paper]

    G.nodes[paper]["x"] = x * 1000
    G.nodes[paper]["y"] = y * 1000
    G.nodes[paper]["physics"] = False
    G.nodes[paper]["size"] = info["node_size"]
    G.nodes[paper]["color"] = color_map[cluster_map[paper]]
    G.nodes[paper]["title"] = (
        f"{info['title']}\n"
        f"{info['author']}\n{info['issued_year']}\n"
        f"Citations: {info['crossref_ref_by_count']}"
    )

# Visualizes network using PyVis
nt = Network(
    height="600px",
    width="1000px",
    notebook=True,
    cdn_resources="in_line"
)

nt.from_nx(G)
nt.show("force_kmeans_network.html")

force_kmeans_network.html

/opt/anaconda3/envs/py37/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [67]:
from IPython.display import HTML
pd.set_option('display.max_colwidth', 10000)

HTML(
    filtered_df[['cluster','file_name','title','author','issued_year','crossref_ref_by_count', 'cites_per_year']]
    .reset_index(drop=True)
    .to_html(index=False)
)

In [68]:
import re

cluster_num = 0
subset_df = filtered_df.loc[filtered_df['cluster'] == cluster_num, ['file_name', 'title', 'author', 'issued_year', 'crossref_ref_by_count']]
subset_df = subset_df.sort_values(by='crossref_ref_by_count', ascending=False)
subset_df['file_name'] = [re.sub(r'.txt', '', name) for name in subset_df['file_name']]
# # !pip install itables
# from itables import show
# show(subset_df.reset_index(drop=True))

In [69]:
len(subset_df)

16

In [70]:
cluster_papers = filtered_df.loc[filtered_df['cluster'] == cluster_num, 'file_name'].to_numpy()

In [71]:
v.aggregate_doc_topics(cluster_papers, normed_sum=True)[:5]

LabeledColumn([(11, 0.30295098), ( 0, 0.19157101), (10, 0.18352993),
               ( 2, 0.11885004), (18, 0.0637316 )],
              dtype=[('i', '<i8'), ('value', '<f4')])

In [72]:
agg_topics = [topic[0] for topic in v.aggregate_doc_topics(cluster_papers, normed_sum=True)[:5]]
v.topics(topic_indices=agg_topics, print_len=25)

[LabeledColumn([('model', 4.7398314e-02), ('data', 2.7909886e-02),
                ('models', 2.0656325e-02), ..., ('≤', 1.5126108e-08),
                ('⋅', 1.5126108e-08), ('λ', 1.5126108e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('et', 1.7831322e-02), ('al', 1.5591688e-02),
                ('participants', 1.2778989e-02), ...,
                ('model', 1.9035179e-08), ('probability', 1.9035179e-08),
                ('probabilities', 1.9035179e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('one', 2.1907536e-02), ('two', 1.9953560e-02),
                ('model', 1.7862890e-02), ..., ('item', 5.1740248e-09),
                ('stimuli', 5.1740248e-09), ('proposition', 5.1740248e-09)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('space', 1.1346714e-02), ('stimulus', 1.0139556e-02),
                ('stimuli', 8.9560691e-03), ...,
                ('replies', 2.9587152e-08), ('fsmds', 2.9587152e-08),
                ('aa', 2.9587152e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('function', 1.7919905e-02), ('models', 1.6640840e-02),
                ('given', 1.5973849e-02), ..., ('response', 9.7508766e-09),
                ('probability', 9.7508766e-09), ('items', 9.7508766e-09)],
               dtype=[('word', 'O'), ('value', '<f4')])]

In [73]:
v.doc_topics(cluster_papers, print_len=1)

[LabeledColumn([( 2, 3.41281921e-01), (10, 3.13004017e-01),
                (18, 2.20906243e-01), ( 8, 1.03124864e-01),
                ( 0, 1.43996831e-02), ( 6, 7.26534845e-03),
                ( 3, 1.29841851e-06), ( 5, 1.29841851e-06),
                (11, 1.29841851e-06), (17, 1.29742887e-06),
                ( 1, 1.29718148e-06), ( 4, 1.29718148e-06),
                ( 9, 1.29718148e-06), ( 7, 1.29718148e-06),
                (15, 1.29718148e-06), (13, 1.29715170e-06),
                (16, 1.29715170e-06), (12, 1.29715056e-06),
                (14, 1.29715056e-06), (19, 1.29715056e-06)],
               dtype=[('topic', '<i8'), ('value', '<f4')]),
 LabeledColumn([(10, 3.1186575e-01), ( 2, 2.8192911e-01),
                (18, 2.7480826e-01), (14, 6.1473306e-02),
                ( 8, 3.6768306e-02), ( 1, 2.3689190e-02),
                ( 0, 9.4474843e-03), ( 3, 1.4546545e-06),
                ( 5, 1.4546545e-06), ( 6, 1.4546545e-06),
                ( 9, 1.4546545e-06), (17, 1.4546545e-06),
                (15, 1.4535457e-06), (11, 1.4532685e-06),
                ( 7, 1.4532685e-06), ( 4, 1.4532685e-06),
                (19, 1.4532685e-06), (12, 1.4532352e-06),
                (13, 1.4532352e-06), (16, 1.4532338e-06)],
               dtype=[('topic', '<i8'), ('value', '<f4')]),
 LabeledColumn([( 2, 4.5489430e-01), (10, 2.5577039e-01),
                (18, 1.7500947e-01), ( 3, 2.3737881e-02),
                ( 6, 2.2982603e-02), ( 7, 2.0069383e-02),
                ( 9, 1.8720672e-02), ( 1, 1.6778525e-02),
                (15, 1.1006035e-02), ( 8, 1.0255616e-03),
                ( 4, 5.4001185e-07), (19, 5.4001185e-07),
                (11, 5.4001185e-07), ( 0, 5.3949736e-07),
                (16, 5.3948503e-07), (17, 5.3948503e-07),
                (12, 5.3948452e-07), ( 5, 5.3948452e-07),
                (13, 5.3948452e-07), (14, 5.3948452e-07)],
               dtype=[('topic', '<i8'), ('value', '<f4')]),
 LabeledColumn([( 2, 3.7441108e-01), (11, 2.1793899e-01),
                (10, 2.1281689e-01), (18, 1.4573383e-01),
                ( 7, 2.2968516e-02), ( 0, 1.8342098e-02),
                ( 3, 7.6021980e-03), (12, 1.6688312e-04),
                ( 6, 1.6539058e-06), ( 9, 1.6539058e-06),
                (17, 1.6526452e-06), ( 1, 1.6526452e-06),
                (14, 1.6523301e-06), ( 5, 1.6523301e-06),
                (16, 1.6523301e-06), (13, 1.6522922e-06),
                ( 8, 1.6522922e-06), (15, 1.6522922e-06),
                ( 4, 1.6522906e-06), (19, 1.6522906e-06)],
               dtype=[('topic', '<i8'), ('value', '<f4')]),
 LabeledColumn([( 2, 4.0014046e-01), (10, 2.2533661e-01),
                (18, 1.7965764e-01), ( 0, 5.7284392e-02),
                (15, 3.4181170e-02), ( 3, 3.4075674e-02),
                ( 6, 2.1416374e-02), ( 7, 2.0150444e-02),
                ( 9, 1.6880125e-02), ( 4, 1.0866956e-02),
                (12, 1.0559720e-06), (14, 1.0559720e-06),
                ( 1, 1.0559720e-06), (19, 1.0559720e-06),
                (17, 1.0551671e-06), ( 8, 1.0549659e-06),
                (16, 1.0549659e-06), (13, 1.0549418e-06),
                ( 5, 1.0549418e-06), (11, 1.0549408e-06)],
               dtype=[('topic', '<i8'), ('value', '<f4')]),
 LabeledColumn([(11, 5.1998794e-01), ( 0, 2.0525385e-01),
                (10, 1.6883461e-01), (15, 9.2399195e-02),
                (17, 1.1242754e-02), (12, 2.2503489e-03),
                (18, 2.2502961e-06), ( 9, 2.2502961e-06),
                ( 7, 2.2485810e-06), ( 5, 2.2485810e-06),
                ( 3, 2.2485810e-06), ( 2, 2.2485810e-06),
                ( 1, 2.2485810e-06), (13, 2.2481522e-06),
                (14, 2.2481522e-06), ( 6, 2.2481522e-06),
                (19, 2.2481522e-06), ( 8, 2.2481006e-06),
                (16, 2.2480986e-06), ( 4, 2.2480986e-06)],
               dtype=[('topic', '<i8'), ('value', '<f4')]),
 LabeledColumn([( 0, 4.0898091e-01), (11, 3.0548707e-01),
                (15, 1.2276690e-01), (10, 1.1241751e-01),
                ( 6, 3.8722757e-02), ( 8, 8.2099186e-03),
                ( 4, 2.3214743e-03), (12, 8.9397439e-04),
                ( 9, 1.8022208e-04), (18, 1.7861191e-06),
                ( 5, 1.7861191e-06), (17, 1.7861191e-06),
                ( 1, 1.7861191e-06), (16, 1.7847577e-06),
                ( 7, 1.7844173e-06), (19, 1.7844173e-06),
                ( 3, 1.7843765e-06), (13, 1.7843748e-06),
                (14, 1.7843748e-06), ( 2, 1.7843748e-06)],
               dtype=[('topic', '<i8'), ('value', '<f4')]),
 LabeledColumn([(11, 4.1860411e-01), ( 0, 2.3485263e-01),
                (10, 2.3399237e-01), (15, 8.0694087e-02),
                (18, 2.3572838e-02), (17, 3.4427610e-03),
                ( 3, 2.7545532e-03), (12, 1.7222416e-03),
                ( 9, 1.7377283e-04), (16, 1.7377247e-04),
                ( 1, 1.7221996e-06), ( 7, 1.7205588e-06),
                ( 6, 1.7205588e-06), ( 5, 1.7205588e-06),
                ( 2, 1.7205588e-06), (14, 1.7205194e-06),
                (13, 1.7205178e-06), ( 8, 1.7205178e-06),
                ( 4, 1.7205178e-06), (19, 1.7205178e-06)],
               dtype=[('topic', '<i8'), ('value', '<f4')]),
 LabeledColumn([( 0, 3.7864155e-01), (11, 2.8080317e-01),
                (10, 1.8331802e-01), (15, 1.2751129e-01),
                ( 5, 1.9076718e-02), ( 6, 9.8933345e-03),
                ( 1, 3.5673991e-04), (12, 3.5673915e-04),
                (17, 3.5355204e-06), (18, 3.5355204e-06),
                ( 8, 3.5355204e-06), ( 4, 3.5328255e-06),
                ( 9, 3.5328255e-06), (13, 3.5328255e-06),
                (14, 3.5321518e-06), ( 2, 3.5321518e-06),
                (16, 3.5321518e-06), (19, 3.5321518e-06),
                ( 7, 3.5320709e-06), ( 3, 3.5320677e-06)],
               dtype=[('topic', '<i8'), ('value', '<f4')]),
 LabeledColumn([(11, 4.33486521e-01), ( 0, 2.62054801e-01),
                (10, 1.46631360e-01), (15, 1.10791504e-01),
                (12, 3.32520343e-02), (17, 1.04944026e-02),
                ( 8, 3.27192177e-03), ( 3, 1.36406311e-06),
                ( 6, 1.36406311e-06), ( 7, 1.36406311e-06),
                ( 9, 1.36406311e-06), (18, 1.36406311e-06),
                ( 5, 1.36276356e-06), ( 1, 1.36276356e-06),
                (13, 1.36273229e-06), (19, 1.36273229e-06),
                (14, 1.36273104e-06), ( 4, 1.36273104e-06),
                (16, 1.36273104e-06), ( 2, 1.36273104e-06)],
               dtype=[('topic', '<i8'), ('value', '<f4')]),
 LabeledColumn([( 0, 3.07454824e-01), (11, 2.63058543e-01),
                (15, 1.71993688e-01), (10, 9.22901109e-02),
                ( 6, 5.36618382e-02), ( 3, 4.38736789e-02),
                (17, 2.28990503e-02), ( 8, 1.67814512e-02),
                ( 2, 1.43344104e-02), (12, 1.34604685e-02),
                ( 9, 1.76538146e-04), (18, 1.74959257e-06),
                ( 7, 1.74959257e-06), ( 4, 1.74959257e-06),
                (14, 1.74959257e-06), ( 1, 1.74959257e-06),
                (13, 1.74792558e-06), ( 5, 1.74792558e-06),
                (19, 1.74788556e-06), (16, 1.74788397e-06)],
               dtype=[('topic', '<i8'), ('value', '<f4')]),
 LabeledColumn([(11, 4.5154983e-01), ( 0, 2.2613874e-01),
                (10, 1.7632172e-01), (15, 5.9259009e-02),
                ( 3, 3.1663578e-02), (17, 2.9049274e-02),
                (12, 1.9318255e-02), ( 5, 6.6824513e-03),
                ( 6, 1.4538093e-06), ( 1, 1.4538093e-06),
                ( 2, 1.4538093e-06), ( 9, 1.4538093e-06),
                ( 8, 1.4538093e-06), (18, 1.4538093e-06),
                (16, 1.4527013e-06), ( 7, 1.4523910e-06),
                (13, 1.4523910e-06), ( 4, 1.4523896e-06),
                (14, 1.4523896e-06), (19, 1.4523896e-06)],
               dtype=[('topic', '<i8'), ('value', '<f4')]),
 LabeledColumn([(11, 5.8396965e-01), ( 0, 2.2937456e-01),
                (10, 1.4810064e-01), (17, 1.8513897e-02),
                ( 5, 1.2644116e-02), (15, 5.5702748e-03),
                (19, 1.8075921e-03), (18, 1.5065423e-06),
                ( 3, 1.5065423e-06), ( 1, 1.5065423e-06),
                ( 8, 1.5053940e-06), ( 6, 1.5053940e-06),
                ( 7, 1.5051070e-06), ( 2, 1.5051070e-06),
                (13, 1.5050724e-06), ( 4, 1.5050724e-06),
                (12, 1.5050711e-06), (14, 1.5050711e-06),
                (16, 1.5050711e-06), ( 9, 1.5050711e-06)],
               dtype=[('topic', '<i8'), ('value', '<f4')]),
 LabeledColumn([(11, 5.9623516e-01), ( 0, 2.0817567e-01),
                (10, 1.4747450e-01), (15, 2.3219384e-02),
                (17, 2.2585429e-02), ( 7, 1.3479469e-03),
                ( 4, 9.5172453e-04), ( 1, 7.9321723e-07),
                ( 2, 7.9321723e-07), ( 9, 7.9321723e-07),
                (12, 7.9321723e-07), (13, 7.9321723e-07),
                ( 8, 7.9261264e-07), ( 3, 7.9261264e-07),
                ( 6, 7.9246149e-07), (18, 7.9244336e-07),
                (14, 7.9244336e-07), (19, 7.9244336e-07),
                ( 5, 7.9244262e-07), (16, 7.9244262e-07)],
               dtype=[('topic', '<i8'), ('value', '<f4')]),
 LabeledColumn([(11, 2.9234949e-01), ( 0, 2.4810311e-01),
                (15, 1.5269183e-01), (10, 8.7850779e-02),
                (12, 8.4954657e-02), (17, 5.7119660e-02),
                ( 3, 4.2317234e-02), ( 2, 3.4594230e-02),
                ( 8, 1.6105304e-06), ( 1, 1.6105304e-06),
                ( 6, 1.6105304e-06), ( 9, 1.6105304e-06),
                (18, 1.6105304e-06), ( 7, 1.6093029e-06),
                ( 4, 1.6093029e-06), (19, 1.6093029e-06),
                ( 5, 1.6089959e-06), (13, 1.6089576e-06),
                (14, 1.6089576e-06), (16, 1.6089576e-06)],
               dtype=[('topic', '<i8'), ('value', '<f4')]),
 LabeledColumn([(11, 4.83743370e-01), ( 0, 2.56632417e-01),
                (10, 1.20454848e-01), (17, 6.48267567e-02),
                (12, 3.35266814e-02), (15, 2.69996524e-02),
                ( 3, 1.37972515e-02), (14, 1.48486447e-06),
                ( 1, 1.48486447e-06), (18, 1.48486447e-06),
                ( 8, 1.48486447e-06), (16, 1.48373272e-06),
                ( 2, 1.48373272e-06), ( 5, 1.48344975e-06),
                (19, 1.48344975e-06), ( 6, 1.48344975e-06),
                ( 7, 1.48344975e-06), (13, 1.48344975e-06),
                ( 9, 1.48344975e-06), ( 4, 1.48341439e-06)],
               dtype=[('topic', '<i8'), ('value', '<f4')])]

In [74]:
v.topics(print_len=25)

[LabeledColumn([('et', 1.7831322e-02), ('al', 1.5591688e-02),
                ('participants', 1.2778989e-02), ...,
                ('model', 1.9035179e-08), ('probability', 1.9035179e-08),
                ('probabilities', 1.9035179e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('item', 1.8723859e-02), ('set', 1.6397031e-02),
                ('items', 1.0185160e-02), ..., ('≤', 4.1016101e-08),
                ('w', 4.1016101e-08), ('δ', 4.1016101e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('space', 1.1346714e-02), ('stimulus', 1.0139556e-02),
                ('stimuli', 8.9560691e-03), ...,
                ('replies', 2.9587152e-08), ('fsmds', 2.9587152e-08),
                ('aa', 2.9587152e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('model', 2.0678805e-02), ('learning', 1.6718490e-02),
                ('category', 1.2606424e-02), ..., ('rosen', 3.7012260e-08),
                ('roschian', 3.7012260e-08), ('aa', 3.7012260e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('utility', 1.9942729e-02), ('decision', 1.5737034e-02),
                ('risk', 1.3123138e-02), ...,
                ('transcendental', 3.3511469e-08),
                ('submodels', 3.3511469e-08), ('∈', 3.2726078e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('u', 7.9492174e-02), ('α', 3.3635315e-02),
                ('β', 3.2659017e-02), ..., ('fixedlength', 3.2435153e-08),
                ('samples', 3.2435153e-08), ('︸', 3.2435153e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('memory', 2.5993897e-02), ('items', 1.5769666e-02),
                ('item', 1.5334666e-02), ..., ('ridge', 3.4251993e-08),
                ('riddled', 3.4251993e-08), ('︸', 3.4251993e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('f', 2.6528398e-02), ('e', 2.4495983e-02),
                ('z', 2.1127639e-02), ..., ('fxc', 2.3770923e-08),
                ('retinally', 2.3770923e-08), ('︸', 2.3770923e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('response', 2.2784494e-02), ('model', 2.2615880e-02),
                ('learning', 2.0356970e-02), ...,
                ('marcum', 2.6764297e-08), ('marczewska', 2.6764297e-08),
                ('maxdy', 2.6764297e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('state', 1.6622949e-02), ('quantum', 1.4929453e-02),
                ('probability', 1.2474833e-02), ...,
                ('fletcherpowell', 3.8056083e-08),
                ('rtresearch', 3.8056083e-08), ('aa', 3.8056083e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('one', 2.1907536e-02), ('two', 1.9953560e-02),
                ('model', 1.7862890e-02), ..., ('item', 5.1740248e-09),
                ('stimuli', 5.1740248e-09), ('proposition', 5.1740248e-09)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('model', 4.7398314e-02), ('data', 2.7909886e-02),
                ('models', 2.0656325e-02), ..., ('≤', 1.5126108e-08),
                ('⋅', 1.5126108e-08), ('λ', 1.5126108e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('f', 8.3647974e-02), ('σ', 5.2904967e-02),
                ('μ', 4.6585765e-02), ..., ('θ', 3.1198656e-08),
                ('ϕ', 3.1198656e-08), ('ω', 3.1198656e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('∈', 6.5812290e-02), ('z', 4.4626985e-02),
                ('f', 2.4575856e-02), ..., ('stahl', 2.0003103e-08),
                ('notthe', 2.0003103e-08), ('vehicles', 2.0003103e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('e', 2.9651018e-02), ('g', 2.1478537e-02),
                ('let', 1.3876706e-02), ..., ('rotates', 2.2644697e-08),
                ('maxdy', 2.2644697e-08), ('ϕ', 2.2113984e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('time', 2.9852744e-02), ('processing', 1.7103627e-02),
                ('response', 1.6134683e-02), ...,
                ('kochenspecker', 2.8837603e-08),
                ('kowalchuk', 2.8837603e-08), ('λ', 2.8161748e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('choice', 3.6647450e-02), ('set', 2.2050343e-02),
                ('preference', 1.5498851e-02), ...,
                ('fcuwp', 4.3560409e-08), ('fcuwq', 4.3560409e-08),
                ('qktvk', 4.3560409e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('θ', 8.0177814e-02), ('α', 5.9952885e-02),
                ('π', 5.7655107e-02), ..., ('xα⊕α≻', 2.8090147e-08),
                ('questions', 2.8090147e-08), ('embodies', 2.8090147e-08)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('function', 1.7919905e-02), ('models', 1.6640840e-02),
                ('given', 1.5973849e-02), ..., ('response', 9.7508766e-09),
                ('probability', 9.7508766e-09), ('items', 9.7508766e-09)],
               dtype=[('word', 'O'), ('value', '<f4')]),
 LabeledColumn([('q', 1.6761938e-01), ('∈', 5.6370370e-02),
                ('l', 2.5291942e-02), ..., ('sadly', 3.1603008e-08),
                ('reconciliation', 3.1603008e-08), ('z', 3.0862342e-08)],
               dtype=[('word', 'O'), ('value', '<f4')])]

# Using Python's Help System

There are many other functions in the InPhO Topic Explorer and the associated `vsm` library. These are extensively documented within the code. 

One little-known feature about Python is its capacity for introspection: by using the `help()` method, one can find out all methods and properties of an object. For example, if one wanted to know what methods could be called on their corpus object, you could run:

In [ ]:
help(c)

You can also get help on particular methods. For example, there are many arguments to `v.topics()` beyond `print_len`. These can be seen by calling `help(v.topics)` without parentheses after `v.topics`:

In [ ]:
help(v.topics)

Calling `help(v.topics())` *with* parentheses will return help for the object reutrned by `v.topics()`, which is a `DataTable`:

In [ ]:
help(v.topics())

It is important to emphasize that this functionality can be used with any python library, including the standard library. For example, one could look at all the functions included in the `math` library by using:

In [7]:
import math
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x[, base])

    Return the logarithm of x to the given base.
    If the base not specified, returns the natural logarithm (base e) of x.

For emphasis, calling `help(math.log(3))` will return the documentation for `float`. Why? First `math.log(3)` will be evaluated, then `help()` will be called on that result: `help(1.0986122886681098)`

In [ ]:
help(math.log(3))

## `help()` and `?`

Alternatively, you can place a `?` before any function to receive help in a separate "frame". This allows you to view help while scrolling up and down the notebook

In [8]:
?math.log

# Additional Examples

This notebook gives some basic building blocks for using the Topic Explorer. Additional examples can be found on GitHub in the [inpho/vsm-demo-notebooks repository](http://github.com/inpho/vsm-demo-notebooks).

# Contact Information
If you have additional questions regarding the InPhO Topic Explorer or have comments on this tutorial, please e-mail [tutorial@hypershelf.org](mailto:tutorial@hypershelf.org).